ENVIRONMENT: Development
LOG_LEVEL: 'info'
COMMERCE_TOOL_AUTH_URL: test
COMMERCE_TOOL_API_HOST: test
CT_SOURCE_PROJECT_KEY: alamy-staging
CT_SOURCE_CLIENT_ID: test
CT_SOURCE_SECRET_NAME: commercetool/staging
CT_DESTINATION_PROJECT_KEY: meraki-development
CT_DESTINATION_URL: test
CT_DESTINATION_ID: test
CT_DESTINATION_SECRET_NAME: commercetool/development
